linters:
  enable:
    - dupl
    - errorlint
    - funlen
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gosec
    - lll
    - misspell
    - whitespace
    - wrapcheck
linters-settings:
  lll:
    line-length: 100
    tab-width: 4
  misspell:
    locale: US
