before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  -
    main: ./cmd/whatsthis/main.go
    goos: [linux]
    goarch: [amd64]
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
