site_name: whatsthis
site_description: Am I on a cloud, in a container, virtualized, or plain bare metal?
copyright: Copyright &copy; 2020 - 2021 Joshua Powers
repo_name: powersj/whatsthis
repo_url: https://github.com/powersj/whatsthis
theme:
  name: material
  favicon: images/favicon.ico
  features:
    - navigation.sections
  font:
    text: Ubuntu
    code: JetBrains Mono
  icon:
    logo: material/developer-board
    repo: fontawesome/brands/github
  palette:
  - scheme: default
    primary: deep purple
    accent: amber
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
nav:
- Overview: index.md
- Install: install.md
- CLI: cli.md
- Internals:
  - Clouds: internals/clouds.md
  - Containers: internals/containers.md
  - Virtualization: internals/virtualization.md
- Contributing:
  - Overview: contributing/overview.md
  - Docs: contributing/documentation.md
  - Versioning: contributing/versioning.md
  - Roadmap: contributing/roadmap.md
