site_name: whatsthis
site_description: Am I on a cloud, in a container, virtualized, or plain bare metal?
site_url: https://powersj.github.io/whatsthis
theme:
  name: material
repo_name: powersj/whatsthis
repo_url: https://github.com/powersj/whatsthis
nav:
- whatsthis: index.md
- cloud.md
- container.md
- virtualiztion.md
